services:
  web:
    build: . # PATH TO DOCKERFILE
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://admin:admin@mongodb/DC_Station
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=DC_Station
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db:/initial_data
      - mongo_data:/data/db

volumes:
  mongo_data: